---
title: "Cv-HengMa"
---
```{r}
git add .
git commit -m 
git push -u origin master
```



## introduction

This website focuses on Heng Ma's personal journey and resume, highlighting their status as a University of Toronto student with limited work experience but a strong interest in their field. Employed in a basic role in multinational trade, HengMa aims to grasp the operational strategies of cross-border trade, linking companies across countries, and initiating international cooperation. Through their work, they have significantly enhanced their English skills, technical proficiency, and cultural understanding, creating a dynamic and energetic image.

[My Cv](Cv-HengMa.pdf)

## Bio

Hengma was born in Luoyang City, Henan Province, China, a region known for its rich history and pleasant climate, located in the Central Plains area. Currently, he is pursuing a double major in Economics and Statistics at the University of Toronto. Hengma has participated in several volunteer experiences, including planning the Confucius Institute New Year's Eve event as part of the Vanpeople activities, as well as offline campus promotional campaigns. He has also gained professional experience through a stint at a multinational foreign trade company, where his role focused on outsourcing activities aimed at fostering understanding and cooperation between two companies, including certain promotional projects. After graduating, Hengma plans to continue his career in international trade, using his knowledge and experience as a foundation to facilitate cooperation between companies from different countries, with a focus on